spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: aryanjohnsharma@gmail.com
    password: qikazskvwrrsbbmq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# 

# moqjgxdbvwpuqzz